---
name: Competition
users:
  - username: admin
    password: changeme123!
teams:
  amount: 15
  nameFormat: Team {{ .Team }}
  password: changeme123!
scoring:
  interval: 30 # seconds 
engine:
  socket: /tmp/compscore.sock
  timeout: 5 # seconds
checks:
  - name: host_a-ssh
    release:
      org: compscore
      repo: ssh
      tag: v1.0.5
    credentials:
      username: ubuntu
      password: changeme
    target: 10.{{ .Team }}.1.1:22
    command: whoami
    expectedOutput: ubuntu
    weight: 2
  - name: example.com-dns
    release:
      org: compscore
      repo: dns
      tag: v1.0.5
    target: 8.8.8.8
    command: A example.com
    expectedOutput: 93.184.216.34
    weight: 1
  - name: host_a-ping
    release:
      org: compscore
      repo: ping
      tag: v1.0.6
    target: 10.{{ .Team }}.1.1
    weight: 1
  - name: host_a-web
    release:
      org: compscore
      repo: web
      tag: v1.0.8
    target: https://google.com
    weight: 2
    command: GET
    options:
      status_code: 200
  - name: host_c-winrm
    release:
      org: compscore
      repo: winrm
      tag: v1.0.3
    credentials:
      username: Administrator
      password: changeme
    target: 10.{{ .Team }}.1.3:5985
    command: whoami
    expectedOutput: Administrator
    weight: 2
    options:
      https: false
      insecure: true
  - name: test.rebex.net-ftp
    release:
      org: compscore
      repo: ftp
      tag: v1.0.4
    credentials:
      username: demo
      password: password
    target: test.rebex.net
    weight: 1
    command: readme.txt
    options:
      exists:
      sha256: b004de45d8a133e9713a369f9c912237e8ad35dd9140c0279d27bada067797f4
  - name: host_c-ldap
    release:
      org: compscore
      repo: ldap
      tag: v1.0.6
    credentials:
      username: cn=admin,dc=example.com,dc=local
      password: password
    target: 10.{{ .Team }}.1.3:389
    weight: 2
    options:
      ldaps: false

