---
name: Competition
web:
  hostname: 127.0.0.1
  port: 8080
  apiPath: /api
teams:
  amount: 15
  nameFormat: Team {{ .Team }}
  password: password
scoring:
  interval: 10 # seconds 
engine:
  socket: /tmp/compscore.sock
  timeout: 5 # seconds
checks:
  - name: host_a-ssh
    release:
      org: compscore
      repo: ssh
      tag: v1.0.2
    credentials:
      username: ubuntu
      password: changeme
    target: 10.{{ .Team }}.1.1:22
    command: whoami
    expectedOutput: ubuntu
    weight: 2
  - name: example.com-dns
    release:
      org: compscore
      repo: dns
      tag: v1.0.1
    target: 8.8.8.8
    command: A example.com
    expectedOutput: 93.184.216.34
    weight: 1
  - name: host_a-ping
    release:
      org: compscore
      repo: ping
      tag: v1.0.3
    target: 10.{{ .Team }}.1.1
    weight: 1
  - name: host_a-web
    release:
      org: compscore
      repo: web
      tag: v1.0.4
    target: https://google.com
    weight: 2
    command: GET
    expectedOutput: status_code=200

