---
name: Competition
web:
  hostname: 127.0.0.1
  port: 8080
  apiPath: /api
teams:
  amount: 15
  nameFormat: Team {{ .Team }}
  password: password
scoring:
  interval: 30 # seconds 
  retries: 3
engine:
  socket: /tmp/compscore.sock
  timeout: 5 # seconds
checks:
  - name: host_a-ssh
    git:
      remote: git@github.com:compscore/ssh.git
      branch: main
    credentials:
      username: ubuntu
      password: changeme
    target: 10.{{ .Team }}.1.1
    port: 22
    command: whoami
    expectedOutput: ubuntu
    weight: 2
  - name: host_a-ssh
    git:
      remote: git@github.com:compscore/ssh.git
      branch: main
    credentials:
      username: kali
      password: changeme
    target: 10.{{ .Team }}.1.2
    port: 22
    command: whoami
    expectedOutput: kali
    weight: 2
  - name: host_a-ping
    git:
      remote: git@github.com:compscore/ping.git
      branch: main
    target: 10.{{ .Team }}.1.1
    weight: 1
