---
server:
  api-path: "/api"
  hostname: "127.0.0.1"
  port: 8080
teams:
  amount: 15
  name-format: "Team %d"
  password: "password"
scoring:
  interval: 30 # seconds 
  retries: 3
checks:
  - name: "host_a-ssh"
    git:
      remote: "git@github.com:compscore/ssh.git"
      branch: "main"
    credential:
      username: "ubuntu"
      password: "changeme"
    target: "10.{ team }.1.1"
    port: 22
    command: "whoami"
    expected-output: "ubuntu"
    weight: 2
  - name: "host_a-ssh"
    git:
      remote: "git@github.com:compscore/ssh.git"
      branch: "main"
    credential:
      username: "kali"
      password: "changeme"
    target: "10.{ team }.1.2"
    port: 22
    command: "whoami"
    expected-output: "kali"
    weight: 2
  - name: "host_a-ping"
    git:
      remote: "git@github.com:compscore/ping.git"
      branch: "main"
    target: "10.{ team }.1.1"
    weight: 1
