---
name: Competition
web:
  hostname: 127.0.0.1
  port: 8080
  apiPath: /api
teams:
  amount: 1
  nameFormat: Team {{ .Team }}
  password: password
scoring:
  interval: 10 # seconds 
engine:
  socket: /tmp/compscore.sock
  timeout: 5 # seconds
checks:
  - name: host_a-ssh
    release:
      org: compscore
      repo: ssh
    credentials:
      username: ubuntu
      password: changeme
    target: 10.{{ .Team }}.1.1:22
    command: whoami
    expectedOutput: ubuntu
    weight: 2
  # - name: host_a-ssh
  #   release:
  #     org: compscore
  #     repo: ssh
  #   credentials:
  #     username: kali
  #     password: changeme
  #   target: 10.{{ .Team }}.1.2
  #   command: whoami
  #   expectedOutput: kali
  #   weight: 2
  # - name: host_a-ping
  #   release:
  #     org: compscore
  #     repo: ping
  #   target: 10.{{ .Team }}.1.1
  #   weight: 1
