version: "3.4"
services:
  frontend:
    container_name: compscore-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - compscore-frontend
      - compscore-backend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - compscore-caddy-data:/data
      - compscore-caddy-config:/config

  engine:
    container_name: compscore-engine
    build:
      context: .
      dockerfile: Dockerfile.engine
    restart: unless-stopped
    networks:
      - compscore-backend

  # db:
  #   container_name: compscore-db
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   networks:
  #     - compscore-backend
  #   volumes:
  #     - compscore-db:/var/lib/postgresql/data

  # redis:
  #   container_name: compscore-redis
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   networks:
  #     - compscore-backend
  #   volumes:
  #     - redis-data:/data

volumes:
  compscore-redis:
    driver: local
  compscore-db:
    driver: local
  compscore-caddy-data:
    driver: local
  compscore-caddy-config:
    driver: local

networks:
  compscore-backend:
  compscore-frontend:
    driver: bridge
