// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Check is the predicate function for check builders.
type Check func(*sql.Selector)

// Round is the predicate function for round builders.
type Round func(*sql.Selector)

// Status is the predicate function for status builders.
type Status func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)
