// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Check is the predicate function for check builders.
type Check func(*sql.Selector)

// Credential is the predicate function for credential builders.
type Credential func(*sql.Selector)

// Round is the predicate function for round builders.
type Round func(*sql.Selector)

// Score is the predicate function for score builders.
type Score func(*sql.Selector)

// Status is the predicate function for status builders.
type Status func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
