basePath: /api
definitions:
  models.AdminLogin:
    description: body of admin login request
    properties:
      team:
        type: string
    type: object
  models.ChangePassword:
    description: body of change password request
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  models.Cookie:
    description: response of login request
    properties:
      domain:
        type: string
      expiration:
        type: integer
      httponly:
        type: boolean
      name:
        type: string
      path:
        type: string
      secure:
        type: boolean
      token:
        type: string
    type: object
  models.Error:
    description: response of login request
    properties:
      error:
        type: string
    type: object
  models.Login:
    description: body of login request
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    name: 1nv8rzim
    url: https://github.com/compsore/compscore/issues
  description: This is the API for the Compscore application
  title: Compscore API
  version: "1.0"
paths:
  /api/admin/login:
    post:
      consumes:
      - application/json
      description: Authenticate into another team and return a JWT
      parameters:
      - description: Team name
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.AdminLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cookie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Authenticate into another team
      tags:
      - admin
  /api/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT
      parameters:
      - description: Username and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cookie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
      summary: Authenticate a user
      tags:
      - auth
  /api/password:
    post:
      consumes:
      - application/json
      description: Change a user's password
      parameters:
      - description: Old and new password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.ChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: Password changed
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Change a user's password
      tags:
      - auth
securityDefinitions:
  ServiceAuth:
    description: JWT for authentication
    in: cookie
    name: auth
    type: apiKey
swagger: "2.0"
