basePath: /api
definitions:
  web.cookie_s:
    description: response of login request
    properties:
      domain:
        type: string
      expiration:
        type: integer
      httponly:
        type: boolean
      name:
        type: string
      path:
        type: string
      secure:
        type: boolean
      token:
        type: string
    type: object
  web.error_s:
    properties:
      error:
        type: string
    type: object
  web.login_s:
    description: body of login request
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    name: 1nv8rzim
    url: https://github.com/compsore/compscore/issues
  description: This is the API for the Compscore application
  title: Compscore API
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT
      parameters:
      - description: Username and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.login_s'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.cookie_s'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.error_s'
      summary: Authenticate a user
      tags:
      - auth
securityDefinitions:
  ServiceAuth:
    description: JWT for authentication
    in: cookie
    name: auth
    type: apiKey
swagger: "2.0"
