// Code generated by ent, DO NOT EDIT.

package check

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the check type in the database.
	Label = "check"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldFunction holds the string denoting the function field in the database.
	FieldFunction = "function"
	// FieldHost holds the string denoting the host field in the database.
	FieldHost = "host"
	// EdgeChecklogs holds the string denoting the checklogs edge name in mutations.
	EdgeChecklogs = "checklogs"
	// Table holds the table name of the check in the database.
	Table = "checks"
	// ChecklogsTable is the table that holds the checklogs relation/edge.
	ChecklogsTable = "check_logs"
	// ChecklogsInverseTable is the table name for the CheckLog entity.
	// It exists in this package in order to avoid circular dependency with the "checklog" package.
	ChecklogsInverseTable = "check_logs"
	// ChecklogsColumn is the table column denoting the checklogs relation/edge.
	ChecklogsColumn = "check_log_check"
)

// Columns holds all SQL columns for check fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldFunction,
	FieldHost,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// FunctionValidator is a validator for the "function" field. It is called by the builders before save.
	FunctionValidator func(string) error
	// HostValidator is a validator for the "host" field. It is called by the builders before save.
	HostValidator func(string) error
)

// OrderOption defines the ordering options for the Check queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByFunction orders the results by the function field.
func ByFunction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFunction, opts...).ToFunc()
}

// ByHost orders the results by the host field.
func ByHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHost, opts...).ToFunc()
}

// ByChecklogsCount orders the results by checklogs count.
func ByChecklogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChecklogsStep(), opts...)
	}
}

// ByChecklogs orders the results by checklogs terms.
func ByChecklogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChecklogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChecklogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChecklogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ChecklogsTable, ChecklogsColumn),
	)
}
