// Code generated by ent, DO NOT EDIT.

package check

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/compscore/compscore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Check {
	return predicate.Check(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Check {
	return predicate.Check(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Check {
	return predicate.Check(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Check {
	return predicate.Check(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Check {
	return predicate.Check(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Check {
	return predicate.Check(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Check {
	return predicate.Check(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldDescription, v))
}

// Function applies equality check predicate on the "function" field. It's identical to FunctionEQ.
func Function(v string) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldFunction, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldHost, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Check {
	return predicate.Check(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Check {
	return predicate.Check(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Check {
	return predicate.Check(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Check {
	return predicate.Check(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Check {
	return predicate.Check(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Check {
	return predicate.Check(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Check {
	return predicate.Check(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Check {
	return predicate.Check(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Check {
	return predicate.Check(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Check {
	return predicate.Check(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Check {
	return predicate.Check(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Check {
	return predicate.Check(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Check {
	return predicate.Check(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Check {
	return predicate.Check(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Check {
	return predicate.Check(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Check {
	return predicate.Check(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Check {
	return predicate.Check(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Check {
	return predicate.Check(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Check {
	return predicate.Check(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Check {
	return predicate.Check(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Check {
	return predicate.Check(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Check {
	return predicate.Check(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Check {
	return predicate.Check(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Check {
	return predicate.Check(sql.FieldContainsFold(FieldDescription, v))
}

// FunctionEQ applies the EQ predicate on the "function" field.
func FunctionEQ(v string) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldFunction, v))
}

// FunctionNEQ applies the NEQ predicate on the "function" field.
func FunctionNEQ(v string) predicate.Check {
	return predicate.Check(sql.FieldNEQ(FieldFunction, v))
}

// FunctionIn applies the In predicate on the "function" field.
func FunctionIn(vs ...string) predicate.Check {
	return predicate.Check(sql.FieldIn(FieldFunction, vs...))
}

// FunctionNotIn applies the NotIn predicate on the "function" field.
func FunctionNotIn(vs ...string) predicate.Check {
	return predicate.Check(sql.FieldNotIn(FieldFunction, vs...))
}

// FunctionGT applies the GT predicate on the "function" field.
func FunctionGT(v string) predicate.Check {
	return predicate.Check(sql.FieldGT(FieldFunction, v))
}

// FunctionGTE applies the GTE predicate on the "function" field.
func FunctionGTE(v string) predicate.Check {
	return predicate.Check(sql.FieldGTE(FieldFunction, v))
}

// FunctionLT applies the LT predicate on the "function" field.
func FunctionLT(v string) predicate.Check {
	return predicate.Check(sql.FieldLT(FieldFunction, v))
}

// FunctionLTE applies the LTE predicate on the "function" field.
func FunctionLTE(v string) predicate.Check {
	return predicate.Check(sql.FieldLTE(FieldFunction, v))
}

// FunctionContains applies the Contains predicate on the "function" field.
func FunctionContains(v string) predicate.Check {
	return predicate.Check(sql.FieldContains(FieldFunction, v))
}

// FunctionHasPrefix applies the HasPrefix predicate on the "function" field.
func FunctionHasPrefix(v string) predicate.Check {
	return predicate.Check(sql.FieldHasPrefix(FieldFunction, v))
}

// FunctionHasSuffix applies the HasSuffix predicate on the "function" field.
func FunctionHasSuffix(v string) predicate.Check {
	return predicate.Check(sql.FieldHasSuffix(FieldFunction, v))
}

// FunctionEqualFold applies the EqualFold predicate on the "function" field.
func FunctionEqualFold(v string) predicate.Check {
	return predicate.Check(sql.FieldEqualFold(FieldFunction, v))
}

// FunctionContainsFold applies the ContainsFold predicate on the "function" field.
func FunctionContainsFold(v string) predicate.Check {
	return predicate.Check(sql.FieldContainsFold(FieldFunction, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Check {
	return predicate.Check(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Check {
	return predicate.Check(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Check {
	return predicate.Check(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Check {
	return predicate.Check(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Check {
	return predicate.Check(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Check {
	return predicate.Check(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Check {
	return predicate.Check(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Check {
	return predicate.Check(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Check {
	return predicate.Check(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Check {
	return predicate.Check(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Check {
	return predicate.Check(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Check {
	return predicate.Check(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Check {
	return predicate.Check(sql.FieldContainsFold(FieldHost, v))
}

// HasChecklogs applies the HasEdge predicate on the "checklogs" edge.
func HasChecklogs() predicate.Check {
	return predicate.Check(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ChecklogsTable, ChecklogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChecklogsWith applies the HasEdge predicate on the "checklogs" edge with a given conditions (other predicates).
func HasChecklogsWith(preds ...predicate.CheckLog) predicate.Check {
	return predicate.Check(func(s *sql.Selector) {
		step := newChecklogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Check) predicate.Check {
	return predicate.Check(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Check) predicate.Check {
	return predicate.Check(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Check) predicate.Check {
	return predicate.Check(func(s *sql.Selector) {
		p(s.Not())
	})
}
