// Code generated by compscore, DO NOT EDIT.
// Import generated from https://github.com/compscore/ftp@v1.0.4

package imports

import (
	ftp "github.com/compscore/ftp"
)

func init() {
	Imports["compscore/ftp"] = ftp.Run
}
