// Code generated by compscore, DO NOT EDIT.

package imports

import "context"

var (
	Imports map[string]func(ctx context.Context, target string, command string, expectedOutput string, username string, password string, options map[string]interface{}) (bool, string) = make(map[string]func(ctx context.Context, target string, command string, expectedOutput string, username string, password string, options map[string]interface{}) (bool, string))
)
