// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/compscore/compscore/pkg/ent"
)

type Mutation struct {
	CreateCheck      *ent.Check      `json:"createCheck"`
	UpdateCheck      *ent.Check      `json:"updateCheck"`
	DeleteCheck      *ent.Check      `json:"deleteCheck"`
	UpdateCredential *ent.Credential `json:"updateCredential"`
	UpdateRound      *ent.Round      `json:"updateRound"`
	DeleteRound      *ent.Round      `json:"deleteRound"`
	UpdateScore      *ent.Score      `json:"updateScore"`
	DeleteScore      *ent.Score      `json:"deleteScore"`
	UpdateStatus     *ent.Status     `json:"updateStatus"`
	CreateUser       *ent.User       `json:"createUser"`
	UpdateUser       *ent.User       `json:"updateUser"`
	DeleteUser       *ent.User       `json:"deleteUser"`
	Login            string          `json:"login"`
}
