// Code generated by ent, DO NOT EDIT.

package round

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the round type in the database.
	Label = "round"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// EdgeChecklogs holds the string denoting the checklogs edge name in mutations.
	EdgeChecklogs = "checklogs"
	// Table holds the table name of the round in the database.
	Table = "rounds"
	// ChecklogsTable is the table that holds the checklogs relation/edge.
	ChecklogsTable = "check_logs"
	// ChecklogsInverseTable is the table name for the CheckLog entity.
	// It exists in this package in order to avoid circular dependency with the "checklog" package.
	ChecklogsInverseTable = "check_logs"
	// ChecklogsColumn is the table column denoting the checklogs relation/edge.
	ChecklogsColumn = "check_log_round"
)

// Columns holds all SQL columns for round fields.
var Columns = []string{
	FieldID,
	FieldNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NumberValidator is a validator for the "number" field. It is called by the builders before save.
	NumberValidator func(int) error
)

// OrderOption defines the ordering options for the Round queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByChecklogsCount orders the results by checklogs count.
func ByChecklogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChecklogsStep(), opts...)
	}
}

// ByChecklogs orders the results by checklogs terms.
func ByChecklogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChecklogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChecklogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChecklogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ChecklogsTable, ChecklogsColumn),
	)
}
