// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChecksColumns holds the columns for the "checks" table.
	ChecksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "function", Type: field.TypeString},
		{Name: "host", Type: field.TypeString},
	}
	// ChecksTable holds the schema information for the "checks" table.
	ChecksTable = &schema.Table{
		Name:       "checks",
		Columns:    ChecksColumns,
		PrimaryKey: []*schema.Column{ChecksColumns[0]},
	}
	// CheckLogsColumns holds the columns for the "check_logs" table.
	CheckLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeBool},
		{Name: "time", Type: field.TypeTime},
		{Name: "check_log_check", Type: field.TypeInt},
		{Name: "check_log_team", Type: field.TypeInt},
		{Name: "check_log_round", Type: field.TypeInt},
	}
	// CheckLogsTable holds the schema information for the "check_logs" table.
	CheckLogsTable = &schema.Table{
		Name:       "check_logs",
		Columns:    CheckLogsColumns,
		PrimaryKey: []*schema.Column{CheckLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "check_logs_checks_check",
				Columns:    []*schema.Column{CheckLogsColumns[4]},
				RefColumns: []*schema.Column{ChecksColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "check_logs_teams_team",
				Columns:    []*schema.Column{CheckLogsColumns[5]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "check_logs_rounds_round",
				Columns:    []*schema.Column{CheckLogsColumns[6]},
				RefColumns: []*schema.Column{RoundsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RoundsColumns holds the columns for the "rounds" table.
	RoundsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "number", Type: field.TypeInt, Unique: true},
	}
	// RoundsTable holds the schema information for the "rounds" table.
	RoundsTable = &schema.Table{
		Name:       "rounds",
		Columns:    RoundsColumns,
		PrimaryKey: []*schema.Column{RoundsColumns[0]},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "number", Type: field.TypeInt, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChecksTable,
		CheckLogsTable,
		RoundsTable,
		TeamsTable,
	}
)

func init() {
	CheckLogsTable.ForeignKeys[0].RefTable = ChecksTable
	CheckLogsTable.ForeignKeys[1].RefTable = TeamsTable
	CheckLogsTable.ForeignKeys[2].RefTable = RoundsTable
}
