// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/compscore/compscore/ent/check"
	"github.com/compscore/compscore/ent/checklog"
	"github.com/compscore/compscore/ent/predicate"
	"github.com/compscore/compscore/ent/round"
	"github.com/compscore/compscore/ent/team"
)

// CheckLogUpdate is the builder for updating CheckLog entities.
type CheckLogUpdate struct {
	config
	hooks    []Hook
	mutation *CheckLogMutation
}

// Where appends a list predicates to the CheckLogUpdate builder.
func (clu *CheckLogUpdate) Where(ps ...predicate.CheckLog) *CheckLogUpdate {
	clu.mutation.Where(ps...)
	return clu
}

// SetError sets the "error" field.
func (clu *CheckLogUpdate) SetError(s string) *CheckLogUpdate {
	clu.mutation.SetError(s)
	return clu
}

// SetNillableError sets the "error" field if the given value is not nil.
func (clu *CheckLogUpdate) SetNillableError(s *string) *CheckLogUpdate {
	if s != nil {
		clu.SetError(*s)
	}
	return clu
}

// ClearError clears the value of the "error" field.
func (clu *CheckLogUpdate) ClearError() *CheckLogUpdate {
	clu.mutation.ClearError()
	return clu
}

// SetStatus sets the "status" field.
func (clu *CheckLogUpdate) SetStatus(b bool) *CheckLogUpdate {
	clu.mutation.SetStatus(b)
	return clu
}

// SetTime sets the "time" field.
func (clu *CheckLogUpdate) SetTime(t time.Time) *CheckLogUpdate {
	clu.mutation.SetTime(t)
	return clu
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (clu *CheckLogUpdate) SetNillableTime(t *time.Time) *CheckLogUpdate {
	if t != nil {
		clu.SetTime(*t)
	}
	return clu
}

// SetCheckID sets the "check" edge to the Check entity by ID.
func (clu *CheckLogUpdate) SetCheckID(id int) *CheckLogUpdate {
	clu.mutation.SetCheckID(id)
	return clu
}

// SetCheck sets the "check" edge to the Check entity.
func (clu *CheckLogUpdate) SetCheck(c *Check) *CheckLogUpdate {
	return clu.SetCheckID(c.ID)
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (clu *CheckLogUpdate) SetTeamID(id int) *CheckLogUpdate {
	clu.mutation.SetTeamID(id)
	return clu
}

// SetTeam sets the "team" edge to the Team entity.
func (clu *CheckLogUpdate) SetTeam(t *Team) *CheckLogUpdate {
	return clu.SetTeamID(t.ID)
}

// SetRoundID sets the "round" edge to the Round entity by ID.
func (clu *CheckLogUpdate) SetRoundID(id int) *CheckLogUpdate {
	clu.mutation.SetRoundID(id)
	return clu
}

// SetRound sets the "round" edge to the Round entity.
func (clu *CheckLogUpdate) SetRound(r *Round) *CheckLogUpdate {
	return clu.SetRoundID(r.ID)
}

// Mutation returns the CheckLogMutation object of the builder.
func (clu *CheckLogUpdate) Mutation() *CheckLogMutation {
	return clu.mutation
}

// ClearCheck clears the "check" edge to the Check entity.
func (clu *CheckLogUpdate) ClearCheck() *CheckLogUpdate {
	clu.mutation.ClearCheck()
	return clu
}

// ClearTeam clears the "team" edge to the Team entity.
func (clu *CheckLogUpdate) ClearTeam() *CheckLogUpdate {
	clu.mutation.ClearTeam()
	return clu
}

// ClearRound clears the "round" edge to the Round entity.
func (clu *CheckLogUpdate) ClearRound() *CheckLogUpdate {
	clu.mutation.ClearRound()
	return clu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (clu *CheckLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, clu.sqlSave, clu.mutation, clu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (clu *CheckLogUpdate) SaveX(ctx context.Context) int {
	affected, err := clu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (clu *CheckLogUpdate) Exec(ctx context.Context) error {
	_, err := clu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clu *CheckLogUpdate) ExecX(ctx context.Context) {
	if err := clu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (clu *CheckLogUpdate) check() error {
	if _, ok := clu.mutation.CheckID(); clu.mutation.CheckCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CheckLog.check"`)
	}
	if _, ok := clu.mutation.TeamID(); clu.mutation.TeamCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CheckLog.team"`)
	}
	if _, ok := clu.mutation.RoundID(); clu.mutation.RoundCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CheckLog.round"`)
	}
	return nil
}

func (clu *CheckLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := clu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(checklog.Table, checklog.Columns, sqlgraph.NewFieldSpec(checklog.FieldID, field.TypeInt))
	if ps := clu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := clu.mutation.Error(); ok {
		_spec.SetField(checklog.FieldError, field.TypeString, value)
	}
	if clu.mutation.ErrorCleared() {
		_spec.ClearField(checklog.FieldError, field.TypeString)
	}
	if value, ok := clu.mutation.Status(); ok {
		_spec.SetField(checklog.FieldStatus, field.TypeBool, value)
	}
	if value, ok := clu.mutation.Time(); ok {
		_spec.SetField(checklog.FieldTime, field.TypeTime, value)
	}
	if clu.mutation.CheckCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.CheckTable,
			Columns: []string{checklog.CheckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(check.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := clu.mutation.CheckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.CheckTable,
			Columns: []string{checklog.CheckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(check.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if clu.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.TeamTable,
			Columns: []string{checklog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := clu.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.TeamTable,
			Columns: []string{checklog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if clu.mutation.RoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.RoundTable,
			Columns: []string{checklog.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := clu.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.RoundTable,
			Columns: []string{checklog.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, clu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checklog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	clu.mutation.done = true
	return n, nil
}

// CheckLogUpdateOne is the builder for updating a single CheckLog entity.
type CheckLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckLogMutation
}

// SetError sets the "error" field.
func (cluo *CheckLogUpdateOne) SetError(s string) *CheckLogUpdateOne {
	cluo.mutation.SetError(s)
	return cluo
}

// SetNillableError sets the "error" field if the given value is not nil.
func (cluo *CheckLogUpdateOne) SetNillableError(s *string) *CheckLogUpdateOne {
	if s != nil {
		cluo.SetError(*s)
	}
	return cluo
}

// ClearError clears the value of the "error" field.
func (cluo *CheckLogUpdateOne) ClearError() *CheckLogUpdateOne {
	cluo.mutation.ClearError()
	return cluo
}

// SetStatus sets the "status" field.
func (cluo *CheckLogUpdateOne) SetStatus(b bool) *CheckLogUpdateOne {
	cluo.mutation.SetStatus(b)
	return cluo
}

// SetTime sets the "time" field.
func (cluo *CheckLogUpdateOne) SetTime(t time.Time) *CheckLogUpdateOne {
	cluo.mutation.SetTime(t)
	return cluo
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (cluo *CheckLogUpdateOne) SetNillableTime(t *time.Time) *CheckLogUpdateOne {
	if t != nil {
		cluo.SetTime(*t)
	}
	return cluo
}

// SetCheckID sets the "check" edge to the Check entity by ID.
func (cluo *CheckLogUpdateOne) SetCheckID(id int) *CheckLogUpdateOne {
	cluo.mutation.SetCheckID(id)
	return cluo
}

// SetCheck sets the "check" edge to the Check entity.
func (cluo *CheckLogUpdateOne) SetCheck(c *Check) *CheckLogUpdateOne {
	return cluo.SetCheckID(c.ID)
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (cluo *CheckLogUpdateOne) SetTeamID(id int) *CheckLogUpdateOne {
	cluo.mutation.SetTeamID(id)
	return cluo
}

// SetTeam sets the "team" edge to the Team entity.
func (cluo *CheckLogUpdateOne) SetTeam(t *Team) *CheckLogUpdateOne {
	return cluo.SetTeamID(t.ID)
}

// SetRoundID sets the "round" edge to the Round entity by ID.
func (cluo *CheckLogUpdateOne) SetRoundID(id int) *CheckLogUpdateOne {
	cluo.mutation.SetRoundID(id)
	return cluo
}

// SetRound sets the "round" edge to the Round entity.
func (cluo *CheckLogUpdateOne) SetRound(r *Round) *CheckLogUpdateOne {
	return cluo.SetRoundID(r.ID)
}

// Mutation returns the CheckLogMutation object of the builder.
func (cluo *CheckLogUpdateOne) Mutation() *CheckLogMutation {
	return cluo.mutation
}

// ClearCheck clears the "check" edge to the Check entity.
func (cluo *CheckLogUpdateOne) ClearCheck() *CheckLogUpdateOne {
	cluo.mutation.ClearCheck()
	return cluo
}

// ClearTeam clears the "team" edge to the Team entity.
func (cluo *CheckLogUpdateOne) ClearTeam() *CheckLogUpdateOne {
	cluo.mutation.ClearTeam()
	return cluo
}

// ClearRound clears the "round" edge to the Round entity.
func (cluo *CheckLogUpdateOne) ClearRound() *CheckLogUpdateOne {
	cluo.mutation.ClearRound()
	return cluo
}

// Where appends a list predicates to the CheckLogUpdate builder.
func (cluo *CheckLogUpdateOne) Where(ps ...predicate.CheckLog) *CheckLogUpdateOne {
	cluo.mutation.Where(ps...)
	return cluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cluo *CheckLogUpdateOne) Select(field string, fields ...string) *CheckLogUpdateOne {
	cluo.fields = append([]string{field}, fields...)
	return cluo
}

// Save executes the query and returns the updated CheckLog entity.
func (cluo *CheckLogUpdateOne) Save(ctx context.Context) (*CheckLog, error) {
	return withHooks(ctx, cluo.sqlSave, cluo.mutation, cluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cluo *CheckLogUpdateOne) SaveX(ctx context.Context) *CheckLog {
	node, err := cluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cluo *CheckLogUpdateOne) Exec(ctx context.Context) error {
	_, err := cluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cluo *CheckLogUpdateOne) ExecX(ctx context.Context) {
	if err := cluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cluo *CheckLogUpdateOne) check() error {
	if _, ok := cluo.mutation.CheckID(); cluo.mutation.CheckCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CheckLog.check"`)
	}
	if _, ok := cluo.mutation.TeamID(); cluo.mutation.TeamCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CheckLog.team"`)
	}
	if _, ok := cluo.mutation.RoundID(); cluo.mutation.RoundCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CheckLog.round"`)
	}
	return nil
}

func (cluo *CheckLogUpdateOne) sqlSave(ctx context.Context) (_node *CheckLog, err error) {
	if err := cluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checklog.Table, checklog.Columns, sqlgraph.NewFieldSpec(checklog.FieldID, field.TypeInt))
	id, ok := cluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checklog.FieldID)
		for _, f := range fields {
			if !checklog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checklog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cluo.mutation.Error(); ok {
		_spec.SetField(checklog.FieldError, field.TypeString, value)
	}
	if cluo.mutation.ErrorCleared() {
		_spec.ClearField(checklog.FieldError, field.TypeString)
	}
	if value, ok := cluo.mutation.Status(); ok {
		_spec.SetField(checklog.FieldStatus, field.TypeBool, value)
	}
	if value, ok := cluo.mutation.Time(); ok {
		_spec.SetField(checklog.FieldTime, field.TypeTime, value)
	}
	if cluo.mutation.CheckCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.CheckTable,
			Columns: []string{checklog.CheckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(check.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cluo.mutation.CheckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.CheckTable,
			Columns: []string{checklog.CheckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(check.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cluo.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.TeamTable,
			Columns: []string{checklog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cluo.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.TeamTable,
			Columns: []string{checklog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cluo.mutation.RoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.RoundTable,
			Columns: []string{checklog.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cluo.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.RoundTable,
			Columns: []string{checklog.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CheckLog{config: cluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checklog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cluo.mutation.done = true
	return _node, nil
}
