// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/compscore/compscore/ent/check"
	"github.com/compscore/compscore/ent/checklog"
	"github.com/compscore/compscore/ent/round"
	"github.com/compscore/compscore/ent/team"
)

// CheckLog is the model entity for the CheckLog schema.
type CheckLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Error message of check
	Error string `json:"error,omitempty"`
	// Status of check
	Status bool `json:"status,omitempty"`
	// Time of check
	Time time.Time `json:"time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CheckLogQuery when eager-loading is set.
	Edges           CheckLogEdges `json:"edges"`
	check_log_check *int
	check_log_team  *int
	check_log_round *int
	selectValues    sql.SelectValues
}

// CheckLogEdges holds the relations/edges for other nodes in the graph.
type CheckLogEdges struct {
	// Check that was run
	Check *Check `json:"check,omitempty"`
	// Team that was checked
	Team *Team `json:"team,omitempty"`
	// Round that the check was run for
	Round *Round `json:"round,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CheckOrErr returns the Check value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckLogEdges) CheckOrErr() (*Check, error) {
	if e.loadedTypes[0] {
		if e.Check == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: check.Label}
		}
		return e.Check, nil
	}
	return nil, &NotLoadedError{edge: "check"}
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckLogEdges) TeamOrErr() (*Team, error) {
	if e.loadedTypes[1] {
		if e.Team == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: team.Label}
		}
		return e.Team, nil
	}
	return nil, &NotLoadedError{edge: "team"}
}

// RoundOrErr returns the Round value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckLogEdges) RoundOrErr() (*Round, error) {
	if e.loadedTypes[2] {
		if e.Round == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: round.Label}
		}
		return e.Round, nil
	}
	return nil, &NotLoadedError{edge: "round"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checklog.FieldStatus:
			values[i] = new(sql.NullBool)
		case checklog.FieldID:
			values[i] = new(sql.NullInt64)
		case checklog.FieldError:
			values[i] = new(sql.NullString)
		case checklog.FieldTime:
			values[i] = new(sql.NullTime)
		case checklog.ForeignKeys[0]: // check_log_check
			values[i] = new(sql.NullInt64)
		case checklog.ForeignKeys[1]: // check_log_team
			values[i] = new(sql.NullInt64)
		case checklog.ForeignKeys[2]: // check_log_round
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckLog fields.
func (cl *CheckLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checklog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cl.ID = int(value.Int64)
		case checklog.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				cl.Error = value.String
			}
		case checklog.FieldStatus:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				cl.Status = value.Bool
			}
		case checklog.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				cl.Time = value.Time
			}
		case checklog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field check_log_check", value)
			} else if value.Valid {
				cl.check_log_check = new(int)
				*cl.check_log_check = int(value.Int64)
			}
		case checklog.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field check_log_team", value)
			} else if value.Valid {
				cl.check_log_team = new(int)
				*cl.check_log_team = int(value.Int64)
			}
		case checklog.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field check_log_round", value)
			} else if value.Valid {
				cl.check_log_round = new(int)
				*cl.check_log_round = int(value.Int64)
			}
		default:
			cl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckLog.
// This includes values selected through modifiers, order, etc.
func (cl *CheckLog) Value(name string) (ent.Value, error) {
	return cl.selectValues.Get(name)
}

// QueryCheck queries the "check" edge of the CheckLog entity.
func (cl *CheckLog) QueryCheck() *CheckQuery {
	return NewCheckLogClient(cl.config).QueryCheck(cl)
}

// QueryTeam queries the "team" edge of the CheckLog entity.
func (cl *CheckLog) QueryTeam() *TeamQuery {
	return NewCheckLogClient(cl.config).QueryTeam(cl)
}

// QueryRound queries the "round" edge of the CheckLog entity.
func (cl *CheckLog) QueryRound() *RoundQuery {
	return NewCheckLogClient(cl.config).QueryRound(cl)
}

// Update returns a builder for updating this CheckLog.
// Note that you need to call CheckLog.Unwrap() before calling this method if this CheckLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (cl *CheckLog) Update() *CheckLogUpdateOne {
	return NewCheckLogClient(cl.config).UpdateOne(cl)
}

// Unwrap unwraps the CheckLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cl *CheckLog) Unwrap() *CheckLog {
	_tx, ok := cl.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckLog is not a transactional entity")
	}
	cl.config.driver = _tx.drv
	return cl
}

// String implements the fmt.Stringer.
func (cl *CheckLog) String() string {
	var builder strings.Builder
	builder.WriteString("CheckLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cl.ID))
	builder.WriteString("error=")
	builder.WriteString(cl.Error)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", cl.Status))
	builder.WriteString(", ")
	builder.WriteString("time=")
	builder.WriteString(cl.Time.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheckLogs is a parsable slice of CheckLog.
type CheckLogs []*CheckLog
