// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/compscore/compscore/ent/check"
	"github.com/compscore/compscore/ent/checklog"
	"github.com/compscore/compscore/ent/round"
	"github.com/compscore/compscore/ent/team"
)

// CheckLogCreate is the builder for creating a CheckLog entity.
type CheckLogCreate struct {
	config
	mutation *CheckLogMutation
	hooks    []Hook
}

// SetError sets the "error" field.
func (clc *CheckLogCreate) SetError(s string) *CheckLogCreate {
	clc.mutation.SetError(s)
	return clc
}

// SetNillableError sets the "error" field if the given value is not nil.
func (clc *CheckLogCreate) SetNillableError(s *string) *CheckLogCreate {
	if s != nil {
		clc.SetError(*s)
	}
	return clc
}

// SetStatus sets the "status" field.
func (clc *CheckLogCreate) SetStatus(b bool) *CheckLogCreate {
	clc.mutation.SetStatus(b)
	return clc
}

// SetTime sets the "time" field.
func (clc *CheckLogCreate) SetTime(t time.Time) *CheckLogCreate {
	clc.mutation.SetTime(t)
	return clc
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (clc *CheckLogCreate) SetNillableTime(t *time.Time) *CheckLogCreate {
	if t != nil {
		clc.SetTime(*t)
	}
	return clc
}

// SetCheckID sets the "check" edge to the Check entity by ID.
func (clc *CheckLogCreate) SetCheckID(id int) *CheckLogCreate {
	clc.mutation.SetCheckID(id)
	return clc
}

// SetCheck sets the "check" edge to the Check entity.
func (clc *CheckLogCreate) SetCheck(c *Check) *CheckLogCreate {
	return clc.SetCheckID(c.ID)
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (clc *CheckLogCreate) SetTeamID(id int) *CheckLogCreate {
	clc.mutation.SetTeamID(id)
	return clc
}

// SetTeam sets the "team" edge to the Team entity.
func (clc *CheckLogCreate) SetTeam(t *Team) *CheckLogCreate {
	return clc.SetTeamID(t.ID)
}

// SetRoundID sets the "round" edge to the Round entity by ID.
func (clc *CheckLogCreate) SetRoundID(id int) *CheckLogCreate {
	clc.mutation.SetRoundID(id)
	return clc
}

// SetRound sets the "round" edge to the Round entity.
func (clc *CheckLogCreate) SetRound(r *Round) *CheckLogCreate {
	return clc.SetRoundID(r.ID)
}

// Mutation returns the CheckLogMutation object of the builder.
func (clc *CheckLogCreate) Mutation() *CheckLogMutation {
	return clc.mutation
}

// Save creates the CheckLog in the database.
func (clc *CheckLogCreate) Save(ctx context.Context) (*CheckLog, error) {
	clc.defaults()
	return withHooks(ctx, clc.sqlSave, clc.mutation, clc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (clc *CheckLogCreate) SaveX(ctx context.Context) *CheckLog {
	v, err := clc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (clc *CheckLogCreate) Exec(ctx context.Context) error {
	_, err := clc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clc *CheckLogCreate) ExecX(ctx context.Context) {
	if err := clc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (clc *CheckLogCreate) defaults() {
	if _, ok := clc.mutation.Time(); !ok {
		v := checklog.DefaultTime()
		clc.mutation.SetTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (clc *CheckLogCreate) check() error {
	if _, ok := clc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CheckLog.status"`)}
	}
	if _, ok := clc.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "CheckLog.time"`)}
	}
	if _, ok := clc.mutation.CheckID(); !ok {
		return &ValidationError{Name: "check", err: errors.New(`ent: missing required edge "CheckLog.check"`)}
	}
	if _, ok := clc.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "CheckLog.team"`)}
	}
	if _, ok := clc.mutation.RoundID(); !ok {
		return &ValidationError{Name: "round", err: errors.New(`ent: missing required edge "CheckLog.round"`)}
	}
	return nil
}

func (clc *CheckLogCreate) sqlSave(ctx context.Context) (*CheckLog, error) {
	if err := clc.check(); err != nil {
		return nil, err
	}
	_node, _spec := clc.createSpec()
	if err := sqlgraph.CreateNode(ctx, clc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	clc.mutation.id = &_node.ID
	clc.mutation.done = true
	return _node, nil
}

func (clc *CheckLogCreate) createSpec() (*CheckLog, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckLog{config: clc.config}
		_spec = sqlgraph.NewCreateSpec(checklog.Table, sqlgraph.NewFieldSpec(checklog.FieldID, field.TypeInt))
	)
	if value, ok := clc.mutation.Error(); ok {
		_spec.SetField(checklog.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := clc.mutation.Status(); ok {
		_spec.SetField(checklog.FieldStatus, field.TypeBool, value)
		_node.Status = value
	}
	if value, ok := clc.mutation.Time(); ok {
		_spec.SetField(checklog.FieldTime, field.TypeTime, value)
		_node.Time = value
	}
	if nodes := clc.mutation.CheckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.CheckTable,
			Columns: []string{checklog.CheckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(check.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.check_log_check = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := clc.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.TeamTable,
			Columns: []string{checklog.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.check_log_team = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := clc.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   checklog.RoundTable,
			Columns: []string{checklog.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.check_log_round = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CheckLogCreateBulk is the builder for creating many CheckLog entities in bulk.
type CheckLogCreateBulk struct {
	config
	builders []*CheckLogCreate
}

// Save creates the CheckLog entities in the database.
func (clcb *CheckLogCreateBulk) Save(ctx context.Context) ([]*CheckLog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(clcb.builders))
	nodes := make([]*CheckLog, len(clcb.builders))
	mutators := make([]Mutator, len(clcb.builders))
	for i := range clcb.builders {
		func(i int, root context.Context) {
			builder := clcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, clcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, clcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, clcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (clcb *CheckLogCreateBulk) SaveX(ctx context.Context) []*CheckLog {
	v, err := clcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (clcb *CheckLogCreateBulk) Exec(ctx context.Context) error {
	_, err := clcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clcb *CheckLogCreateBulk) ExecX(ctx context.Context) {
	if err := clcb.Exec(ctx); err != nil {
		panic(err)
	}
}
