name: Run GoLang Code Checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  check:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - name: Compile
        run: go build main.go
      - name: Unit Tests
        run: go test -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=10m
