name: Run Typescript Code Checks

on:
  push:
    # paths:https://github.com/1nv8rzim/ops-bot-iii/tree/slash-command-delete-birthday
    #   - "frontend/**"
    branches:
      - main
  pull_request:
    # paths:
    #   - "frontend/**"
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Check TypeScript Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm i

      - name: Compile TypeScript
        run: npm run build

      - name: Run ESLint
        run: npx eslint 'src/**/*.{ts,tsx}' --quiet
